server:
  port: 9090

spring:
  application:
    name: distancelearning-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: http://localhost:8080/
          predicates:
            - Path=/distancelearning-authuser/**
        - id: course-service
          uri: http://localhost:8081/
          predicates:
            - Path=/distancelearning-course/**

